export interface EpisodeSegment {
    /**
     * The string id of the segment - generated by combining the episode id & the segment number
     */
    id: number;
    /**
     * The text of the segment
     */
    text: string;
    /**
     * Start time of the segment in milliseconds
     */
    startTimeMS: string;
    /**
     * End time of the segment in milliseconds
     */
    endTimeMS: string;
    /**
     * The likelihood score of the segment being an advertisement - between 0 and 1
     * 
     * TODO: This needs to be implemented, by adding a pass over the transcript with an LLM, to calculate the advertisement likelihood score based on surrounding context
     * For now, will always be null
     */
    adLikelihoodScore: number | null;
}