packages:
  - packages/client
  - packages/config
  - packages/constants
  - packages/linting
  - packages/logging
  - packages/database
  - packages/s3
  - packages/types
  - packages/ingestion/rss-retrieval-lambda
  - packages/ingestion/process-audio-lambda
  - packages/ingestion/srt-indexing-lambda
  - packages/search/search-lambda
  # Listed outside of /packages, because /sites is a top-level directory,
  # determining all 'sites' deployed by this repository
  - sites
catalog:
  '@orama/orama': ^3.1.7
  '@orama/plugin-data-persistence': ^3.1.7
  typescript: ^5.3.3
  '@aws-sdk/client-cloudfront': ^3.787.0
  '@aws-sdk/client-lambda': ^3.787.0
  '@aws-sdk/client-s3': ^3.787.0
  '@aws-sdk/credential-provider-sso': ^3.787.0
  '@aws-sdk/lib-storage': ^3.787.0
  '@aws-sdk/s3-request-presigner': ^3.787.0
  fs-extra: ^11.3.0
  '@types/fs-extra': ^11.0.4
  loglevel: ^1.9.2
  rolldown: ^1.0.0-beta.8
  tsx: ^4.7.0
  srt-parser-2: ^1.2.3
  xml2js: ^0.6.2
  '@types/xml2js': ^0.4.14
  vitest: ^1.6.1 # CURSOR-TODO - update to 3.2.3
  # ESLint dependencies for workspace-wide linting
  eslint: ^9.29.0
  '@eslint/js': ^9.29.0
  '@typescript-eslint/eslint-plugin': ^8.34.1
  '@typescript-eslint/parser': ^8.34.1
  'eslint-plugin-react-hooks': ^5.2.0
  'eslint-plugin-react-refresh': ^0.4.14
  'eslint-plugin-unused-imports': ^4.1.4
  typescript-eslint: ^8.34.1
  globals: ^15.13.0
injectWorkspacePackages: true
ignoredBuiltDependencies:
  - '@tailwindcss/oxide'
